import React from "react";
import Head from "next/head";

import Footer from "../Footer";
import Navbar from "../Navbar";
import styles from "./Layout.module.scss";

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div>
      <Head>
        <title>le pressing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar />
        {children}
      </main>
      <Footer />
    </div>
  );
}
