import React from "react";
import Head from "next/head";

import Footer from "../Footer";
import Navbar from "../Navbar";
import styles from "./Layout.module.scss";
import { useSelector } from "react-redux";
import { RootState } from "../../redux/store";

export default function Layout({ children }: { children: React.ReactNode }) {
  const { modalView } = useSelector((state: RootState) => state.navbar);

  const under = modalView !== 0;
  const layoutClass = `${styles.layout} ${under ? styles.under : ""}`;

  return (
    <div className={layoutClass}>
      <Head>
        <title>le pressing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar />
        {children}
      </main>
      <Footer />
    </div>
  );
}
